kubectl delete -f 04_backend-secret.yaml
kubectl delete -f 05_backend-service.yaml
kubectl delete -f 06_backend.yaml
kubectl delete -f 07_frontend-configmap.yaml
kubectl delete -f 08_frontend-service.yaml
kubectl delete -f 09_frontend.yaml
kubectl delete -f 10_ingress.yaml
kubectl delete -f 11_mongodb-persistent-volume.yaml
kubectl delete -f 12_mongodb-persistent-volume-claim.yaml
kubectl delete -f 13_mongodb-secret.yaml
kubectl delete -f 14_mongodb-service.yaml
kubectl delete -f 15_mongodb.yaml
