kubectl delete -f 01_frontend.yaml
kubectl delete -f 02_frontend-service.yaml
kubectl delete -f 03_frontend-configmap.yaml
kubectl delete -f 04_ingress.yaml
kubectl delete -f 05_backend.yaml
kubectl delete -f 06_backend-service.yaml
kubectl delete -f 07_backend-secret.yaml
kubectl delete -f 08_mongodb.yaml
kubectl delete -f 09_mongodb-service.yaml
kubectl delete -f 10_mongodb-secret.yaml
kubectl delete -f 11_mongodb-persistent-volume.yaml
kubectl delete -f 12_mongodb-persistent-volume-claim.yaml