kubectl apply -f 01_frontend.yaml
kubectl apply -f 02_frontend-service.yaml
kubectl apply -f 03_frontend-configmap.yaml
kubectl apply -f 04_ingress.yaml
kubectl apply -f 05_backend.yaml
kubectl apply -f 06_backend-service.yaml
kubectl apply -f 07_backend-secret.yaml
kubectl create -f 08_mongodb.yaml
kubectl apply -f 09_mongodb-service.yaml
kubectl apply -f 10_mongodb-secret.yaml
kubectl create -f 11_mongodb-persistent-volume.yaml
kubectl create -f 12_mongodb-persistent-volume-claim.yaml