kubectl apply -f 04_backend-secret.yaml
kubectl apply -f 05_backend-service.yaml
kubectl apply -f 06_backend.yaml
kubectl apply -f 07_frontend-configmap.yaml
kubectl apply -f 08_frontend-service.yaml
kubectl apply -f 09_frontend.yaml
kubectl apply -f 10_ingress.yaml
kubectl apply -f 11_mongodb-persistent-volume.yaml
kubectl apply -f 12_mongodb-persistent-volume-claim.yaml
kubectl apply -f 13_mongodb-secret.yaml
kubectl apply -f 14_mongodb-service.yaml
kubectl apply -f 15_mongodb.yaml
